name: autodoc
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    name: test autodoc
    steps:
      - name: Markdown autodocs
      - uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          commit_message: Apply automatic document updates
          output_file_paths: '[./README.md]'
